// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQMq5O5sdS4kG8SE_Y03z4l_eyvbLCDU',
    appId: '1:399720239528:web:6f17a733d3d17127b80d9d',
    messagingSenderId: '399720239528',
    projectId: 'final-app-f0be8',
    authDomain: 'final-app-f0be8.firebaseapp.com',
    storageBucket: 'final-app-f0be8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhpSm-DIXCJNGFQUG-VtBoS7xYsUvcZ8I',
    appId: '1:399720239528:android:79f607abd5e4bd8fb80d9d',
    messagingSenderId: '399720239528',
    projectId: 'final-app-f0be8',
    storageBucket: 'final-app-f0be8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnegWbitIT5zfoSNLW7DBvh7mCTDS6350',
    appId: '1:399720239528:ios:dc2a4a13fa2835f0b80d9d',
    messagingSenderId: '399720239528',
    projectId: 'final-app-f0be8',
    storageBucket: 'final-app-f0be8.firebasestorage.app',
    iosBundleId: 'com.example.stockwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnegWbitIT5zfoSNLW7DBvh7mCTDS6350',
    appId: '1:399720239528:ios:dc2a4a13fa2835f0b80d9d',
    messagingSenderId: '399720239528',
    projectId: 'final-app-f0be8',
    storageBucket: 'final-app-f0be8.firebasestorage.app',
    iosBundleId: 'com.example.stockwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByQMq5O5sdS4kG8SE_Y03z4l_eyvbLCDU',
    appId: '1:399720239528:web:2669e5be49bb0614b80d9d',
    messagingSenderId: '399720239528',
    projectId: 'final-app-f0be8',
    authDomain: 'final-app-f0be8.firebaseapp.com',
    storageBucket: 'final-app-f0be8.firebasestorage.app',
  );
}
